### ISSUE TITLE
cp949 오류

### ISSUE THREAD

**Issue by Forgot09** [kty0205/OpenRPG#2]
게임 파일이 손상 되었다 길래 코드 좀 만지니까 cp949 때문에 파일을 못 불러 옵니다. 풀리퀘는 못하겠어서 이슈로 보냅니다

**Comment by kty0205** [comment]
원본코드가 아닌 사용자가 직접 수정한 코드의 버그는 제가 해결할 수 없습니다.
CP949 오류를 해결하려면 TXT파일을 저장할때 인코딩 방식을 UTF-8로 변경하신다음 저장해주세요
